# Generated by Django 2.1.7 on 2019-03-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_api_api', '0002_add_picture_field_to_shop'),
        ('mdp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='mdp_api_api.Shop'),
        ),
    ]
