# Generated by Django 2.1.7 on 2019-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_api_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
