# Generated by Django 2.1.7 on 2019-03-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_api_api', '0002_add_picture_field_to_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdp_api_api.ShopRegion')),
            ],
            options={
                'ordering': ['slug'],
                'abstract': False,
            },
        ),
    ]
