# Generated by Django 2.1.7 on 2019-03-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_api_api', '0003_frenchdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mdp_api_api.FrenchDepartment'),
        ),
        migrations.AlterField(
            model_name='frenchdepartment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='mdp_api_api.ShopRegion'),
        ),
    ]
