# Generated by Django 2.1.7 on 2019-03-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_api_api', '0005_populate_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='region',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='state',
        ),
        migrations.AlterField(
            model_name='shop',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdp_api_api.FrenchDepartment'),
        ),
    ]
